;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Actor.State.Rotate",NewTagName="Actor.State.Rotating")
+GameplayTagRedirects=(OldTagName="Character.State.Dodging",NewTagName="Character.State.IsDodging")
+GameplayTagRedirects=(OldTagName="Character.State.Invincible",NewTagName="Character.State.Invinsible")
+GameplayTagRedirects=(OldTagName="Character.Attack.Combo",NewTagName="Character.Attack.ComboAttack")
+GameplayTagRedirects=(OldTagName="GameplayCue.AttackBlockReaction",NewTagName="GameplayCue.AttackBlockedReaction")
+GameplayTagRedirects=(OldTagName="Event.ParrySuccess",NewTagName="Event.Parry.Success")
+GameplayTagRedirects=(OldTagName="HitReaction",NewTagName="AttackReaction")
+GameplayTagRedirects=(OldTagName="AttackReaction2Reaction",NewTagName="Event.Reaction2Reaction")
+GameplayTagRedirects=(OldTagName="Combat.Melee.HeavyAttack",NewTagName="Combat.Melee.Attack.Heavy")
+GameplayTagRedirects=(OldTagName="Combat.Melee.Attack",NewTagName="Combat.Melee.Attack.Light")
+GameplayTagRedirects=(OldTagName="CanDodge",NewTagName="CantDodge")
+GameplayTagRedirects=(OldTagName="Event.Hi",NewTagName="Event.Hit")
+GameplayTagRedirects=(OldTagName="Event.Block.End",NewTagName="Event.BlockEnd")
+GameplayTagRedirects=(OldTagName="Event.Block.ReInput",NewTagName="Event.BlockReInput")
+GameplayTagRedirects=(OldTagName="Event.Block.DirectEnd",NewTagName="Event.BlockDirectEnd")
+GameplayTagRedirects=(OldTagName="Combat.Melee.Parryin",NewTagName="Combat.Melee.Parrying")
+GameplayTagRedirects=(OldTagName="Event.NextCombo",NewTagName="Event.AttackReInput")
+GameplayTagRedirects=(OldTagName="HitCount",NewTagName="AttackedCounter")
+GameplayTagRedirects=(OldTagName="Item.Weapon",NewTagName="Item.Equipment.Weapon")
+GameplayTagRedirects=(OldTagName="Item.Equipment.Weapon.Sword_001",NewTagName="Item.Equipment.Weapon.001")
+GameplayTagRedirects=(OldTagName="Item.Equipment.Weapon.Sword_002",NewTagName="Item.Equipment.Weapon.002")
+GameplayTagRedirects=(OldTagName="Item.Equipment.Weapon.Sword_003",NewTagName="Item.Equipment.Weapon.003")
+GameplayTagRedirects=(OldTagName="Item.Armor",NewTagName="Item.Equipment.Armor")
+GameplayTagRedirects=(OldTagName="",NewTagName="")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Actor.State.Rotating",DevComment="")
+GameplayTagList=(Tag="Animation.ParrySuccessMotion",DevComment="")
+GameplayTagList=(Tag="AttackedCounter",DevComment="")
+GameplayTagList=(Tag="AttackReaction",DevComment="")
+GameplayTagList=(Tag="BT.CanBlock",DevComment="")
+GameplayTagList=(Tag="CanEnterAttack",DevComment="")
+GameplayTagList=(Tag="CantDodge",DevComment="")
+GameplayTagList=(Tag="Character.Action.Attack",DevComment="")
+GameplayTagList=(Tag="Character.Action.AttackHitCheck",DevComment="")
+GameplayTagList=(Tag="Character.Action.Block",DevComment="")
+GameplayTagList=(Tag="Character.Action.Dash",DevComment="")
+GameplayTagList=(Tag="Character.Action.Dodge",DevComment="")
+GameplayTagList=(Tag="Character.Action.GiveCanDoge",DevComment="")
+GameplayTagList=(Tag="Character.Action.Jump",DevComment="")
+GameplayTagList=(Tag="Character.Action.NormalAttack",DevComment="")
+GameplayTagList=(Tag="Character.Animation.CanStopMotion",DevComment="")
+GameplayTagList=(Tag="Character.Attack.CanBlock",DevComment="")
+GameplayTagList=(Tag="Character.Attack.CanParry",DevComment="")
+GameplayTagList=(Tag="Character.Attack.ComboAttack",DevComment="")
+GameplayTagList=(Tag="Character.Attack.CommandAttack",DevComment="")
+GameplayTagList=(Tag="Character.Attack.DashDodgeAttack",DevComment="")
+GameplayTagList=(Tag="Character.Attack.JumpAttack",DevComment="")
+GameplayTagList=(Tag="Character.State.CanDodge",DevComment="")
+GameplayTagList=(Tag="Character.State.Invinsible",DevComment="")
+GameplayTagList=(Tag="Character.State.IsAttacking",DevComment="")
+GameplayTagList=(Tag="Character.State.IsBlocking",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDashing",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDodging",DevComment="")
+GameplayTagList=(Tag="Character.State.IsJumping",DevComment="")
+GameplayTagList=(Tag="Character.State.IsParrying",DevComment="")
+GameplayTagList=(Tag="Combat.Hit",DevComment="")
+GameplayTagList=(Tag="Combat.MaxPosture",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Attack.Finisher",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Attack.Finisher.Ambush",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Attack.Finisher.Back",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Attack.Finisher.MaxPosture",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Attack.Heavy",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Attack.Light",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Block",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Blocking",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Parry",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Parrying",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.SpecialAttack",DevComment="")
+GameplayTagList=(Tag="Combat.Melee.Sting",DevComment="")
+GameplayTagList=(Tag="Combat.Parryed",DevComment="")
+GameplayTagList=(Tag="Combat.SuccessParry",DevComment="")
+GameplayTagList=(Tag="Damage.Melee",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Enemy.CanBlock",DevComment="")
+GameplayTagList=(Tag="Enemy.Combat.Block",DevComment="")
+GameplayTagList=(Tag="Enemy.Combat.BlockReaction",DevComment="")
+GameplayTagList=(Tag="Enemy.Combat.NormalAttack",DevComment="")
+GameplayTagList=(Tag="Enemy.Combat.Parry",DevComment="")
+GameplayTagList=(Tag="Enemy.Combat.Parryed",DevComment="")
+GameplayTagList=(Tag="Enemy.Combat.SpecialAttack",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Started",DevComment="")
+GameplayTagList=(Tag="Event.AttackReInput",DevComment="")
+GameplayTagList=(Tag="Event.Block",DevComment="")
+GameplayTagList=(Tag="Event.BlockDirectEnd",DevComment="")
+GameplayTagList=(Tag="Event.BlockEnd",DevComment="")
+GameplayTagList=(Tag="Event.BlockingDamaged",DevComment="")
+GameplayTagList=(Tag="Event.BlockReInput",DevComment="")
+GameplayTagList=(Tag="Event.BlockToFinisher",DevComment="")
+GameplayTagList=(Tag="Event.DashEnd",DevComment="")
+GameplayTagList=(Tag="Event.DashStart",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.StartAttack.Heavy",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.StartAttack.Light",DevComment="")
+GameplayTagList=(Tag="Event.EnemyAttack",DevComment="")
+GameplayTagList=(Tag="Event.EnemySpecialAttack",DevComment="")
+GameplayTagList=(Tag="Event.Finisher",DevComment="")
+GameplayTagList=(Tag="Event.FinisherHit",DevComment="")
+GameplayTagList=(Tag="Event.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Event.Hit",DevComment="")
+GameplayTagList=(Tag="Event.MaxPosture",DevComment="")
+GameplayTagList=(Tag="Event.Parry.Success",DevComment="")
+GameplayTagList=(Tag="Event.Parryed",DevComment="")
+GameplayTagList=(Tag="Event.Reaction2Reaction",DevComment="")
+GameplayTagList=(Tag="Event.SpawAbility",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AttackBlockedReaction",DevComment="")
+GameplayTagList=(Tag="GameplayCue.CameraShake",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.AttackHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Item.Open",DevComment="")
+GameplayTagList=(Tag="GameplayCue.MeleeDamageReaction",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Shake",DevComment="")
+GameplayTagList=(Tag="Inventory.Food",DevComment="")
+GameplayTagList=(Tag="Inventory.NonExpandableItem",DevComment="")
+GameplayTagList=(Tag="Inventory.Potion",DevComment="")
+GameplayTagList=(Tag="Inventory.Scroll",DevComment="")
+GameplayTagList=(Tag="Inventory.Weapon",DevComment="")
+GameplayTagList=(Tag="Item.Consumable",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Belt.001",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Boots.001",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Cuirass.001",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Gloves.001",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Head",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Head.001",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Head.002",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Mask",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Mask.001",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Pants.001",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Weapon",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Weapon.002",DevComment="")
+GameplayTagList=(Tag="Item.Inventory",DevComment="")
+GameplayTagList=(Tag="Locomotion.Dash",DevComment="")
+GameplayTagList=(Tag="Locomotion.Dodge",DevComment="")
+GameplayTagList=(Tag="Player.Combat.Block",DevComment="")
+GameplayTagList=(Tag="Player.Combat.BlockReaction",DevComment="")
+GameplayTagList=(Tag="Player.Combat.Finisher",DevComment="")
+GameplayTagList=(Tag="Player.Combat.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Player.Combat.Parry",DevComment="")
+GameplayTagList=(Tag="Player.Combat.Parryed",DevComment="")
+GameplayTagList=(Tag="Player.Resurrection",DevComment="")
+GameplayTagList=(Tag="ReInput.Dodge",DevComment="")
+GameplayTagList=(Tag="SkipEndMontage",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Block",DevComment="")
+GameplayTagList=(Tag="State.Blocking",DevComment="")
+GameplayTagList=(Tag="State.BlockReaction",DevComment="")
+GameplayTagList=(Tag="State.CanCounter",DevComment="")
+GameplayTagList=(Tag="State.CanParry",DevComment="")
+GameplayTagList=(Tag="State.Death",DevComment="")
+GameplayTagList=(Tag="State.Dodging",DevComment="")
+GameplayTagList=(Tag="State.Finished",DevComment="")
+GameplayTagList=(Tag="State.Hit",DevComment="")
+GameplayTagList=(Tag="State.IgnoreHitReaction",DevComment="")
+GameplayTagList=(Tag="State.MaxPosture",DevComment="")
+GameplayTagList=(Tag="State.Parryed",DevComment="")
+GameplayTagList=(Tag="State.Parrying",DevComment="")
+GameplayTagList=(Tag="State.SpecialAttacking",DevComment="")
+GameplayTagList=(Tag="Tests.Adrenaline.Decrease",DevComment="")
+GameplayTagList=(Tag="Tests.Adrenaline.Increase",DevComment="")
+GameplayTagList=(Tag="Tests.Exp.Increase",DevComment="")
+GameplayTagList=(Tag="Tests.Health.Decrease",DevComment="")
+GameplayTagList=(Tag="Tests.Health.Increase",DevComment="")
+GameplayTagList=(Tag="Tests.Posture.Decrease",DevComment="")
+GameplayTagList=(Tag="Tests.Posture.Increase",DevComment="")
+GameplayTagList=(Tag="Tests.Stamina.Decrease",DevComment="")
+GameplayTagList=(Tag="Tests.Stamina.Increase",DevComment="")
+GameplayTagList=(Tag="Weapons",DevComment="")
+GameplayTagList=(Tag="Weapons.Right",DevComment="")

